# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.5.2

# Add your logstash plugins setup here
#RUN logstash-plugin install logstash-filter-multiline # 添加logstash-filter-multiline插件
#RUN logstash-plugin install logstash-filter-date # 添加logstash-filter-date插件


